os:
  - osx
  
env:
  - QTBREWVER=5.9
  
language: cpp
  
compiler:
  - clang
  
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 jq python@3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install dmgbuild; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export QTDIR=$(brew info --json=v1 qt | jq -r '.[0].bottle.stable.cellar + "/" + .[0].name + "/" + .[0].installed[0].version'); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ORIONCONFIG=multimedia; fi
  - $QTDIR/bin/qmake orion.pro CONFIG+=$ORIONCONFIG
  - make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash distfiles/deploy_mac.sh; fi
  - mkdir -p artifacts
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dmgbuild -s distfiles/settings.py "Orion $TRAVIS_TAG" "orion-$TRAVIS_TAG.dmg"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv "orion-$TRAVIS_TAG.dmg" artifacts/; fi
  
deploy:
    - provider: releases
      # To use this, create a Github token with the "public_repo" permission, and create an env var GITHUB_API_KEY in the Travis' project settings, making sure "Display value in build log" is set to OFF
      api_key: '$GITHUB_API_KEY'
      file: 'artifacts/orion-$TRAVIS_TAG.dmg'
      skip_cleanup: true
      prerelease: true
      on:
        tags: false
        all_branches: true
